//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMVCRazor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURADETALLE
    {
        public int Id_Factura { get; set; }
        public int NumLinea { get; set; }
        public Nullable<int> Id_FacturaDetalle { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<int> Id_Articulo { get; set; }
        public Nullable<double> Precio { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual ARTICULO ARTICULO1 { get; set; }
        public virtual FACTURA FACTURA { get; set; }
        public virtual FACTURA FACTURA1 { get; set; }
    }
}
