//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMVCRazor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDORE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENDEDORE()
        {
            this.FACTURAS = new HashSet<FACTURA>();
            this.VENDEDORES1 = new HashSet<VENDEDORE>();
        }
    
        public int IdVendedor { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public Nullable<short> CodigoPostal { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public Nullable<int> IdVendedorSupervisor { get; set; }
    
        public virtual CIUDADE CIUDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENDEDORE> VENDEDORES1 { get; set; }
        public virtual VENDEDORE VENDEDORE1 { get; set; }
    }
}
